#!/bin/bash

defaults write -g ApplePressAndHoldEnabled -bool false
defaults write com.apple.finder AppleShowAllFiles YES
defaults write com.apple.dock pinning -string start
defaults write com.apple.dock persistent-apps -array
defaults write com.apple.dock autohide -boolean true
defaults write com.apple.dock orientation -string right
sudo killall Dock

xcode-select --install

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install bash-git-prompt nvm

brew tap homebrew/cask

brew cask install google-chrome visual-studio-code iterm2 flycut
# dropbox hammerspoon xquartz inkscape vlc smoothscroll

ln -s ~/dotfiles/.gitconfig ~/dotfiles/.gitignore ~/
ln -s ~/dotfiles/.bash_profile ~/

#ln -s ~/dotfiles/init.lua ~/.hammerspoon

# Inject Postgres.app bin path
#echo "export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin" >> ~/.zshrc
