#!/bin/bash

defaults write com.apple.finder AppleShowAllFiles YES
defaults write com.apple.dock pinning -string start
defaults write com.apple.dock persistent-apps -array
sudo killall Dock

xcode-select --install

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install bash-git-prompt

brew tap caskroom/cask

brew cask install google-chrome atom iterm2 vlc xquartz inkscape flycut
# dropbox hammerspoon

ln -s ~/dotfiles/.gitconfig ~/dotfiles/.gitignore ~/
ln -s ~/dotfiles/.bash_profile ~/

#ln -s ~/dotfiles/init.lua ~/.hammerspoon

# Inject Postgres.app bin path
#echo "export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin" > ~/.profile
